import { nicknameDefaults } from './nicknameColors';
import { safeChatDefaults } from './safeChat';
import type { ChatTheme, Settings } from './models';
import { automaticAppearance } from './chatAppearance';
import { desktopDefaults } from './preferences';
const base: ChatTheme = {
  appearance: automaticAppearance(),
  nicknameColors: nicknameDefaults('random'),
  id: 'modern',
  name: 'Modern',
  background: '#151719',
  textColor: '#e5e7eb',
  fontFamily: 'Segoe UI',
  fontSize: 14,
  usernameFontWeight: 600,
  showAvatar: true,
  avatarSize: 34,
  showBadges: true,
  showPlatformIcon: true,
  showTimestamps: true,
  messageSpacing: 12,
  borderRadius: 10,
  maxMessages: 100,
  animation: 'fade',
  layout: 'modern',
  lineHeight: 1.6,
  opacity: 0,
  hideCommands: false,
  hideBots: false,
  multiline: true,
  maxLength: 1000,
  platforms: ['twitch', 'youtube'],
};
export const themes: ChatTheme[] = [
  base,
  {
    ...base,
    id: 'minimal',
    name: 'Minimal',
    layout: 'minimal',
    showAvatar: false,
    showBadges: false,
    showTimestamps: false,
    showPlatformIcon: false,
    appearance: { ...automaticAppearance(), density: 'compact' },
    messageSpacing: 4,
  },
  {
    ...base,
    id: 'bubble',
    name: 'Bubble',
    layout: 'bubble',
    borderRadius: 18,
    messageBackground: '#302b39',
  },
  {
    ...base,
    id: 'twitch',
    name: 'Twitch-like',
    layout: 'twitch',
    appearance: { ...automaticAppearance(), density: 'compact' },
    showAvatar: false,
    messageSpacing: 4,
  },
  {
    ...base,
    id: 'youtube',
    name: 'YouTube-like',
    layout: 'youtube',
    appearance: { ...automaticAppearance(), density: 'spacious' },
    avatarSize: 24,
    messageSpacing: 6,
  },
  {
    ...base,
    id: 'overlay',
    name: 'Overlay',
    layout: 'overlay',
    background: '#000000',
    opacity: 0,
    shadow: true,
    showTimestamps: false,
    showAvatar: false,
  },
  {
    ...base,
    id: 'neon',
    name: 'Neon',
    layout: 'neon',
    textColor: '#eee4ff',
    background: '#19141f',
  },
];
export const defaultSettings: Settings = {
  safeChat: safeChatDefaults(),
  desktop: desktopDefaults(),
  theme: 'dark',
  accent: '#c299ff',
  uiScale: 100,
  developerMode: false,
  onboardingComplete: false,
  activeTheme: 'modern',
};
